/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/child.component';
const styles_ChildComponent:any[] = ([] as any[]);
export const RenderType_ChildComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ChildComponent,data:{}});
export function View_ChildComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['HOLY SHIT I\'M A CHILD THAT WAS LOADED'])),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵeld(4,0,(null as any),(null as any),1,'h2',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(5,(null as any),['My name is ',''])),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    ']))],(null as any),(_ck,_v) => {
    var _co:i1.ChildComponent = _v.component;
    const currVal_0:any = _co.name;
    _ck(_v,5,0,currVal_0);
  });
}
export function View_ChildComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'child-plugin',
      ([] as any[]),(null as any),(null as any),(null as any),View_ChildComponent_0,
      RenderType_ChildComponent)),i0.ɵdid(1,49152,(null as any),0,i1.ChildComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ChildComponentNgFactory:i0.ComponentFactory<i1.ChildComponent> = i0.ɵccf('child-plugin',
    i1.ChildComponent,View_ChildComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL25pY2tiZWxsaW5nL0Rlc2t0b3AvYW5ndWxhci1keW5hbWljLWNoaWxkcmVuLW1hc3Rlci9jaGlsZC9zcmMvYXBwL2NoaWxkLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9uaWNrYmVsbGluZy9EZXNrdG9wL2FuZ3VsYXItZHluYW1pYy1jaGlsZHJlbi1tYXN0ZXIvY2hpbGQvc3JjL2FwcC9jaGlsZC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9uaWNrYmVsbGluZy9EZXNrdG9wL2FuZ3VsYXItZHluYW1pYy1jaGlsZHJlbi1tYXN0ZXIvY2hpbGQvc3JjL2FwcC9jaGlsZC5jb21wb25lbnQudHMuQ2hpbGRDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL25pY2tiZWxsaW5nL0Rlc2t0b3AvYW5ndWxhci1keW5hbWljLWNoaWxkcmVuLW1hc3Rlci9jaGlsZC9zcmMvYXBwL2NoaWxkLmNvbXBvbmVudC50cy5DaGlsZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxoMT5IT0xZIFNISVQgSSdNIEEgQ0hJTEQgVEhBVCBXQVMgTE9BREVEPC9oMT5cbiAgICA8aDI+TXkgbmFtZSBpcyB7e25hbWV9fTwvaDI+XG4gICAgIiwiPGNoaWxkLXBsdWdpbj48L2NoaWxkLXBsdWdpbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSw4Q0FDSTtNQUFBO01BQUEsNENBQUk7TUFBQSw2Q0FBMEM7TUFBQSxhQUM5QztNQUFBLHdFQUFJO2FBQUEsc0NBQXdCO01BQUE7O0lBQXhCO0lBQUE7Ozs7b0JDRlI7TUFBQTsrQkFBQSxVQUFBO01BQUE7OzsifQ==
